[project]
name = "litellmdemo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langfuse>=3.2.1",
    "litellm[proxy]>=1.74.6",
    "opentelemetry-api>=1.35.0",
    "opentelemetry-sdk>=1.35.0",
]
